name: kpopmerchapplication
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  get: ^4.6.6
  dio: ^5.7.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.1
  dartz: ^0.10.1
  connectivity_plus: ^4.0.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  salomon_bottom_bar: ^3.3.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.4.3
  image_cropper: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/

  fonts:
    - family: IBM Plex Sans Thai
      fonts:
        - asset: assets/fonts/IBMPlexSansThai-Regular.ttf
        - asset: assets/fonts/IBMPlexSansThai-Bold.ttf
          weight: 700
